# TempoStack - Distributed tracing backend with gateway for COO UI integration
# Gateway enabled with RBAC disabled for simplified multi-tenant access
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: sample
  namespace: tracing-system
spec:
  storage:
    secret:
      name: my-storage-secret
      type: s3
  storageSize: 1Gi
  retention:
    global:
      traces: 48h
  replicationFactor: 1
  template:
    gateway:
      enabled: true
      rbac:
        enabled: false
    queryFrontend:
      jaegerQuery:
        enabled: false
    distributor:
      tls:
        enabled: false
