apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# West site: creates a local proxy service to consume
# the REST API backend exposed by the east site

resources:
  - ../../base
  - listener.yaml
