apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxies-monitor
  namespace: ossm-httpbin
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /stats/prometheus
      relabelings:
        - action: keep
          regex: istio-proxy
          sourceLabels:
            - __meta_kubernetes_pod_container_name
        - action: keep
          sourceLabels:
            - __meta_kubernetes_pod_annotationpresent_prometheus_io_scrape
        - action: replace
          sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: namespace
        - action: replace
          replacement: ossm-3
          targetLabel: mesh_id
  selector:
    matchExpressions:
      - key: istio-prometheus-ignore
        operator: DoesNotExist
