apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  namespace: coo-service-mesh
  labels:
    app: istiod
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchLabels:
      app: istiod
  endpoints:
  - port: http-monitoring
    interval: 15s
    path: /metrics
