apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace-tracing-system.yaml
- namespace-opentelemetrycollector.yaml
- tempostack.yaml
- otel-collector-rbac.yaml
- opentelemetrycollector.yaml
