apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- uiplugin-tracing.yaml
- uiplugin-dashboards.yaml
- uiplugin-logging.yaml
- uiplugin-monitoring.yaml
- uiplugin-troubleshooting-panel.yaml
