apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespace: istio-cni
  values:
    cni:
      ambient:
        reconcileIptablesOnStartup: true
  profile: ambient
