apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  profile: ambient
  namespace: istio-cni
