apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- istio-system-namespace.yaml
- ztunnel-namespace.yaml
- istiocr.yaml
- istiocni.yaml
- ztunnel.yaml
- istio-telemetry.yaml
