apiVersion: sailoperator.io/v1alpha1
kind: ZTunnel
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespace: ztunnel
  profile: ambient
