apiVersion: sailoperator.io/v1
kind: ZTunnel
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespace: ztunnel
  version: v1.28.8
