# Database tier - only accessible from backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: netpolicy-demo
  labels:
    app: database
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        tier: database
    spec:
      containers:
        - name: database
          image: quay.io/openshifttest/hello-openshift:1.2.0
          ports:
            - containerPort: 8080
          env:
            - name: RESPONSE
              value: "Data from Database"
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: netpolicy-demo
  labels:
    app: database
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: database

