apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo

resources:
- namespace.yaml
- bookinfo.yaml
- traffic-generator-configmap.yaml
- traffic-generator.yaml
- pod-monitor.yaml